export const estudios = [
  { cat: "Hormonas", nombre: "17 ALFA HIDROXI PROGESTERONA (17AOHP4)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$440.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Radiología", nombre: "ABDOMEN AP (SIMPLE DE ABDOMEN)", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "ABDOMEN DE PIE – EN DECUBITO", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Inmunología", nombre: "AC. ANTI 21 HIDROXILASA (ADRENAL 21 HIDROXILASA)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$6,040.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI BETA 2 GLUCOPROTEÍNA IgA, IgG, IgM", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$2,390.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI CARDIOLIPINA IGG", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,210.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI CARDIOLIPINA IGM", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,180.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI CHIKUNGUNYA IgG e IgM", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,635.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI CHLAMYDIA TRACHOMATIS IGG", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$800.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI CITOMEGALOVIRUS IgG", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$675.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI CITOMEGALOVIRUS IgM", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$700.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI CITOPLASMA DE NEUTRÓFILOS (P Y C ANCA)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,515.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI DENGUE IgG, IgM", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$940.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI DNA DOBLE CADENA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$730.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI DNA UNA CADENA (DESNATURALIZADA)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$935.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI EPSTEIN BARR IgG*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$915.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI EPSTEIN BARR IgM*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$680.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI FOSFOLÍPIDOS IgG, IgM", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,450.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI HELICOBACTER PYLORI IGG", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$810.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI HELICOBACTER PYLORI IGM", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$800.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI HERPES I IgG, IgM", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,375.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI HERPES II IgG, IgM", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,360.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI LKM IGG (LIVER-KIDNERY MICROSOME)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,095.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI MICROSOMALES TOTALES (PEROXIDASA)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$710.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI MITOCONDRIA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$980.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI MÚSCULO LISO IgG", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$870.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI NUCLEARES* (ANA)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$630.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI NUCLEARES POR INMUNOFLUORESCENCIA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$730.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI PEPTIDO CICLICO CITRULINADO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,275.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI RNP", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$715.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI SMITH IGG (SM)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$710.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTISSA (LA)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$890.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTISSA (RO)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$735.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI TIROGLOBULINA TOTAL (AC. ANTI TIROIDES)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$735.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI TIROIDES TPO,TG", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$640.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI TOXOPLASMA GONDII IGG", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$655.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI TOXOPLASMA GONDII IGM", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$660.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI TRANSGLUTAMINASA TISULAR IgA, IgG", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$2,640.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "AC. ANTI TREPONEMA PALLIDUM IgG POR IFI", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$850.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "ACIDO FOLICO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$840.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "ACIDOS BILIARES TOTALES Y FRACCIONADOS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$4,900.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Uroanálisis", nombre: "ÁCIDO ÚRICO EN ORINA DE 24 HRS.", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$105.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "ÁCIDO ÚRICO EN SANGRE", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$155.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Toxicología", nombre: "ÁCIDO VALPROÍCO* (VALPROATO)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$555.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "ADN", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$9,050.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Marcadores Tumorales", nombre: "Ag. PROSTÁTICO ESPECÍFICO (PSA)", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$640.00", desc: "No requiere preparación previa." },
  { cat: "Química Sanguínea", nombre: "ALBÚMINA EN SUERO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$210.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "ALDOLASA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$355.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "ALDOSTERONA EN SUERO*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,125.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "ALFAFETOPROTEÍNA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$460.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "ALGORITMO CANCER OVARIO (AG CA-125, AG HE4)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,685.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "ALOANTICUERPOS PRE-TRANSPLANTE", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$3,880.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Microbiología", nombre: "AMIBA EN FRESCO", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$180.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "AMILASA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$400.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "AMONIO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$440.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "ANDROSCOPIA", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$810.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Hormonas", nombre: "ANDROSTENEDIONA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$580.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hematología", nombre: "ANTICOAGULANTE CIRCULATORIO LUPICO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,090.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "ANTIESTREPTOLISINAS (AEL)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$240.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "ANTÍGENO CA 125", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$615.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "ANTÍGENO CA 15-3", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$610.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "ANTÍGENO CA 19-9", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$580.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "ANTÍGENO CA 27-29**", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,800.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "ANTÍGENO CA 72-4*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,390.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "ANTÍGENO CARCINOEMBRIONARIO (CEA)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$390.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "ANTÍGENO HE4", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$4,000.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "ANTÍGENO PROSTÁTICO ESPECIFICO TOTAL Y LIBRE", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$780.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "ANTÍGENO PROSTÁTICO LIBRE (PSA-L)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$500.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "ANTÍGENO SUPERFICIE HEPAT B (AUSTRALIA) HBS AG", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$740.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Radiología", nombre: "AP – LAT HÚMERO", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "ARTICULACION TEMPO MANDIBULAR BOCA ABIERTA", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "ARTICULACION TEMPO MANDIBULAR BOCA CERRADA", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Uroanálisis", nombre: "AZÚCARES REDUCTORES", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$135.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Anatomía Patológica", nombre: "BAAF ($ CADA SENO)", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$870.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Microbiología", nombre: "BAAR DE ESPUTO", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$360.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "BETA 2 MICROGLOBULINA EN SUERO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$690.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Uroanálisis", nombre: "BICARBONATO EN ORINA OCASIONAL", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$1,085.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "BILIRRUBINAS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$300.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hematología", nombre: "BIOMETRÍA HEMÁTICA COMPLETA", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$275.00", desc: "No requiere preparación previa." },
  { cat: "Anatomía Patológica", nombre: "BIOPSIA (ANÁLISIS)", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$1,265.00", desc: "No requiere preparación previa." },
  { cat: "Anatomía Patológica", nombre: "BIOPSIA DE CÉRVIX (TOMA)", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$800.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Anatomía Patológica", nombre: "BIOPSIA DE ENDOMETRIO (TOMA)", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$1,200.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Toxicología", nombre: "BÚSQUEDA DE DROGAS (ANTIDOPING)", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$1,230.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "CADWELL", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "CALCANEO AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "CALCANEO AXIAL", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "CALCANEO AXIAL BILATERAL", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "CALCANEO BILATERAL (SÓLO EN LATERAL)", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Uroanálisis", nombre: "CALCIO EN ORINA DE 24 HRS.", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$120.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "CALCIO EN SUERO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$240.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "CALCITONINA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$775.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Toxicología", nombre: "CARBAMACEPINA (TEGRETOL)*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$660.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Radiología", nombre: "CEFALOPELVIMETRIA", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,210.00", desc: "No requiere preparación previa." },
  { cat: "Inmunología", nombre: "CÉLULAS L.E.", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$120.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "CISTATINA C", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,410.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Radiología", nombre: "CISTOGRAMA", tipo: "Radiología", indicacion: "ESPECIALES", precio: "$2,660.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Anatomía Patológica", nombre: "CITOLOGÍA CÉRVICO – VAGINAL (PPV)", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$490.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Anatomía Patológica", nombre: "CITOLOGÍA DE LÍQUIDOS VARIOS", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$690.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Anatomía Patológica", nombre: "CITOLOGÍA EN MOCO FECAL", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$200.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "CITOQUIMICO LCR", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$315.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Radiología", nombre: "CLAVÍCULA AP", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "CLAVÍCULA BILATERAL AP", tipo: "Radiología", indicacion: "NINGUNA", precio: "$730.00", desc: "No requiere preparación previa." },
  { cat: "Química Sanguínea", nombre: "CO2", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$100.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Radiología", nombre: "CODO AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "CODO BILATERAL AP - LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLANGIOGRAFIA EN SONDA T", tipo: "Radiología", indicacion: "ESPECIALES", precio: "$2,780.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "COLESTEROL", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$265.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Radiología", nombre: "COLON POR ENEMA", tipo: "Radiología", indicacion: "ESPECIALES", precio: "$2,150.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Anatomía Patológica", nombre: "COLPOSCOPIA", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$760.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Radiología", nombre: "COLUMNA CERVICAL AP", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA CERVICAL AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA CERVICAL AP – LAT OBLICUAS DINÁMICAS", tipo: "Radiología", indicacion: "NINGUNA", precio: "$3,270.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA CERVICAL AP – LAT Y DINÁMICAS", tipo: "Radiología", indicacion: "NINGUNA", precio: "$2,180.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA CERVICAL AP – LAT Y OBLICUAS", tipo: "Radiología", indicacion: "NINGUNA", precio: "$2,180.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA CERVICAL DINAMICAS", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA CERVICAL LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA CERVICAL OBLICUAS", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA CERVICAL TRANSORAL", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA COMPLETA AP – LAT (6 RADIOGRAFÍAS)", tipo: "Radiología", indicacion: "NINGUNA", precio: "$3,270.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA COMPLETA AP – LAT Y TRANSORAL", tipo: "Radiología", indicacion: "NINGUNA", precio: "$3,810.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA DORSAL AP", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA DORSAL AP – LAT DINAMICAS", tipo: "Radiología", indicacion: "NINGUNA", precio: "$2,180.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA DORSAL AP – LAT OBLICUAS", tipo: "Radiología", indicacion: "NINGUNA", precio: "$2,180.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA DORSAL AP Y LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA DORSAL DINAMICAS", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA DORSAL LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA DORSAL OBLICUAS", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA DORSAL Y LUMBAR AP Y LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,690.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA LUMBAR AP Y LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA LUMBOSACRA AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA LUMBOSACRA AP – LAT, OBLI Y DINAM", tipo: "Radiología", indicacion: "NINGUNA", precio: "$3,270.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA LUMBOSACRA AP - LAT Y DINAMICAS", tipo: "Radiología", indicacion: "NINGUNA", precio: "$2,180.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA LUMBOSACRA AP – LAT Y OBLICUAS", tipo: "Radiología", indicacion: "NINGUNA", precio: "$2,180.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA LUMBOSACRA DINAMICAS", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA LUMBOSACRA OBLICUAS", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "COLUMNA SACRO-COXIGEA AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Inmunología", nombre: "COMPLEMENTO C-1 ESTERASA INHIBIDOR", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,760.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "COMPLEMENTO C-3", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$435.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "COMPLEMENTO C-4", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$590.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "COMPLEMENTO C-5", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,400.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hematología", nombre: "COOMS DIRECTO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$275.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hematología", nombre: "COOMS INDIRECTO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$385.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Microbiología", nombre: "COPROCULTIVO", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$370.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Microbiología", nombre: "COPROLÓGICO", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$440.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Microbiología", nombre: "COPROPARASITOSCÓPICO (1 MUESTRA)", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$200.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Microbiología", nombre: "COPROPARASITOSCÓPICO (2 MUESTRAS)", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$290.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Microbiología", nombre: "COPROPARASITOSCÓPICO (3 MUESTRAS)", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$320.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Hormonas", nombre: "CORTISOL MATUTINO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$300.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Radiología", nombre: "CRÁNEO AP", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "CRÁNEO AP – LAT (TAWN = AP)", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,090.00", desc: "No requiere preparación previa." },
  { cat: "Química Sanguínea", nombre: "CREATIN FOSFOCINASA – CK MB", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$360.00", desc: "No requiere preparación previa." },
  { cat: "Química Sanguínea", nombre: "CREATIN FOSFOCINASA – CK T", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$320.00", desc: "No requiere preparación previa." },
  { cat: "Química Sanguínea", nombre: "CREATININA EN SUERO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$250.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "CRISTALOGRAFÍA DE MOCO CERVICAL", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$265.00", desc: "No requiere preparación previa." },
  { cat: "Marcadores Tumorales", nombre: "CUADRUPE MARCADOR", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$4,950.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Radiología", nombre: "CÚBITO Y RADIO AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "CÚBITO Y RADIO BILATERAL AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,090.00", desc: "No requiere preparación previa." },
  { cat: "Microbiología", nombre: "CULTIVO DE CHLAMYDIA TRACHOMATIS, MYCOPLAS", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$5,920.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Microbiología", nombre: "CULTIVO DE EXPECTORACIÓN", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$650.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Microbiología", nombre: "CULTIVO DE EXUDADO CÉRVICO – VAGINAL", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$650.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Microbiología", nombre: "CULTIVO DE EXUDADO (DIVERSOS)", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$725.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Microbiología", nombre: "CULTIVO DE EXUDADO FARÍNGEO", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$650.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Microbiología", nombre: "CULTIVO DE EXUDADO NASAL", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$650.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Microbiología", nombre: "CULTIVO DE EXUDADO URETRAL", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$650.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Microbiología", nombre: "CULTIVO DE EXUDADO VULVO VAGINAL", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$650.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Microbiología", nombre: "CULTIVO ÓTICO", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$650.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "CURVA DE TOLERANCIA A LA GLUCOSA", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$550.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Hormonas", nombre: "DEHIDROEPIANDROSTERONA (DHEA)*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$500.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "DEHIDROEPIANDROSTERONA SULFATO (DHEA-S)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$450.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "DENGUE DÚO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,125.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Tomografía", nombre: "DENSITOMETRIA COLUMNA Y CADERA", tipo: "Tomografía", indicacion: "NO CALCIO", precio: "$770.00", desc: "Evita suplementos de calcio 48 horas antes del estudio." },
  { cat: "Tomografía", nombre: "DENSITOMETRIA CUERPO COMPLETO", tipo: "Tomografía", indicacion: "NO CALCIO", precio: "$1,320.00", desc: "Evita suplementos de calcio 48 horas antes del estudio." },
  { cat: "Uroanálisis", nombre: "DEPURACIÓN DE CREATININA", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$425.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Uroanálisis", nombre: "DEPURACIÓN DE UREA", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$125.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "DESHIDROGENASA LÁCTICA (DHL)", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$240.00", desc: "No requiere preparación previa." },
  { cat: "Química Sanguínea", nombre: "DETECCIÓN VIRUS RESPIRATORIO SINCITIAL (ANTÍGE)", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$1,810.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "DIAGNÓSTICO DE EMBARAZO EN ORINA", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$250.00", desc: "No requiere preparación previa." },
  { cat: "Química Sanguínea", nombre: "DIAGNÓSTICO DE EMBARAZO EN SANGRE", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$275.00", desc: "No requiere preparación previa." },
  { cat: "Toxicología", nombre: "DIFENILHIDANTOINA (FENITOÍNA) (EPAMIN)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$410.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hematología", nombre: "DÍMERO D*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$885.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "DUO MARCADOR", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$3,800.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "ELECTROCARDIOGRAMA EN REPOSO", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Química Sanguínea", nombre: "ELECTROFORESIS DE PROTEÍNAS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$570.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Uroanálisis", nombre: "ELECTROLITOS SERICO EN ORINA 24 HR. (Na, K, Cal)", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$285.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "ELECTROLITOS SÉRICOS COMPLETOS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$770.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "ELECTROLITOS SÉRICOS (Na, K, Cl)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$450.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "ELECTROLITOS SÉRICOS (Na, K, Cl Y Ca)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$600.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "EOSINÓFILOS EN MOCO NASAL - 2 FOSAS NASALES", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$240.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Radiología", nombre: "ESCANOMETRÍA", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,330.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "ESOFAGOGRAMA", tipo: "Radiología", indicacion: "ESPECIALES", precio: "$1,330.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Hormonas", nombre: "ESPERMATOBIOSCOPIA", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$510.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Radiología", nombre: "ESTERNON LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "ESTERNON PA", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Hormonas", nombre: "ESTRADIOL (E2)*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$345.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "ESTRÓGENOS TOTALES", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$375.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "EXÁMENES PRENUPCIALES CON HOJA", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$365.00", desc: "No requiere preparación previa." },
  { cat: "Química Sanguínea", nombre: "EXÁMENES PRENUPCIALES SIN HOJA", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$290.00", desc: "No requiere preparación previa." },
  { cat: "Uroanálisis", nombre: "EXAMEN GENERAL DE ORINA", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$165.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Toxicología", nombre: "ÉXTASIS MDMA", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$1,025.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Anatomía Patológica", nombre: "EXTIRPACIÓN DE PÓLIPO (TOMA)", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$1,350.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Inmunología", nombre: "FACTOR REUMATOIDE", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$360.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Radiología", nombre: "FÉMUR AP", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "FÉMUR AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "FÉMUR BILATERAL AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$2,050.00", desc: "No requiere preparación previa." },
  { cat: "Toxicología", nombre: "FENCICLIDINA (PCP, POLVO DE ANGEL)", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$270.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "FENILALANINA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$210.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Toxicología", nombre: "FENOBARBITAL*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$535.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "FERRITINA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$540.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hematología", nombre: "FIBRINÓGENO*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$215.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Uroanálisis", nombre: "FILTRADO GLOMERULAR", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$320.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Radiología", nombre: "FISTULOGRAFIA", tipo: "Radiología", indicacion: "ESPECIALES", precio: "$2,310.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Hematología", nombre: "FÓRMULA ROJA", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$165.00", desc: "No requiere preparación previa." },
  { cat: "Química Sanguínea", nombre: "FOSFATASA ACIDA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$165.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "FOSFATASA ÁCIDA/FRACCIÓN PROSTÁTICA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$535.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "FOSFATASA ÁCIDA TOTAL", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$140.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "FOSFATASA ALCALINA EN SUERO (ALP)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$240.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "FÓSFORO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$275.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "FRACCIÓN BETA DE HGC", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$650.00", desc: "No requiere preparación previa." },
  { cat: "Química Sanguínea", nombre: "FRACCIÓN LIBRE BETA G CORIÓNICA H (TUMORAL)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,890.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "FRACCION PROSTATICA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$210.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hematología", nombre: "FROTIS DE SANGRE PERIFÉRICA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$550.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "FRUCTOSAMINA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,415.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "GASOMETRÍA", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$1,595.00", desc: "No requiere preparación previa." },
  { cat: "Química Sanguínea", nombre: "GGT (GAMMA-GLUTAMIL TRANSFERASA)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$220.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "GLUCOSA EN SUERO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$110.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "GLUCOSA POSTPRANDIAL", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$110.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "GLUCOSA POSTPRANDIAL 2 MTAS", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$220.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Uroanálisis", nombre: "GONADOTROFINAS CORIONICAS EN ORINA 24 HRS", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$760.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Hematología", nombre: "GRUPO SANGUÍNEO Y FACTOR RH", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$110.00", desc: "No requiere preparación previa." },
  { cat: "Microbiología", nombre: "HELICOBACTER PYLORI EN HECES", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$2,650.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Hematología", nombre: "HEMOGLOBINA GLICOSILADA (HbA1c)", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$600.00", desc: "No requiere preparación previa." },
  { cat: "Inmunología", nombre: "HEPATITIS A, B, C Y D MARCADORES COMPLETOS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$4,390.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "HEPATITIS A, B Y C MARCADORES IGG, IGM", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$3,420.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "HEPATITIS A IGG*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$715.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "HEPATITIS A IGM*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$785.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "HEPATITIS A Y B MARCADORES IGG, IGM", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$2,795.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "HEPATITIS B Ac.*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$660.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "HEPATITIS B AC. CORE*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$600.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "HEPATITIS B CORE (Ac. IgM)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$580.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "HEPATITIS B (HBeAc)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$495.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "HEPATITIS B (HBe Ag)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$655.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "HEPATITIS B Y C MARCADORES", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$2,745.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "HEPATITIS C TOTALES (HCVAC)*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$675.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "HEPATITIS D (AC.)**", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,740.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "HEPATITIS E IGG", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$980.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "HEPATITIS E IGM", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,635.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "HEPATITIS PERFIL B IGG E IGM", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$2,720.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "HIERRO SÉRICO (FE)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$220.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Anatomía Patológica", nombre: "HISPATOLÓGICO CHICO (3 cm.)", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$1,265.00", desc: "No requiere preparación previa." },
  { cat: "Anatomía Patológica", nombre: "HISPATOLÓGICO DE ÚTERO CON CA", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$4,550.00", desc: "No requiere preparación previa." },
  { cat: "Anatomía Patológica", nombre: "HISPATOLÓGICO EXTRA GRANDE (MÁS DE 40 cm.)", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$3,300.00", desc: "No requiere preparación previa." },
  { cat: "Anatomía Patológica", nombre: "HISPATOLÓGICO GRANDE (MÁS DE 15 cm.)", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$1,980.00", desc: "No requiere preparación previa." },
  { cat: "Anatomía Patológica", nombre: "HISPATOLÓGICO MEDIANO (3 cm. A 15 cm.)", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$1,650.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "HISTEROSALPINGOGRAFÍA", tipo: "Radiología", indicacion: "ESPECIALES", precio: "$2,530.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "HISTO (CÁLCULOS PIEDRAS CUALQUIER CANTIDAD)", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "Consultar", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "HOMBRO 1 PROYECCIÓN AP", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "HOMBRO 2 PROYECCIONES", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "HOMBROS BILATERAL 2 PROYECCIONES", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "HOMBRO TRANS-TORACICO", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Hormonas", nombre: "HORMONA ADRENOCORTICOTRÓFICA (ACTH)*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$590.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "HORMONA ANTI MULERIANA AMH/MIS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$3,000.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "HORMONA DEL CRECIMIENTO*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$680.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "HORMONA ESTIMULANTE DE TIROIDES (TSH)*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$215.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "HORMONA FOLÍCULO ESTIMULANTE (FSH)*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$270.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "HORMONA LUTEINIZANTE (HL)*", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$260.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Radiología", nombre: "HUECO PÉLVICO", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Inmunología", nombre: "INMUNOGLOBULINA A IgA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$445.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "INMUNOGLOBULINA E IgE", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$400.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "INMUNOGLOBULINA G IgG", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$390.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "INMUNOGLOBULINA IgA, IgE, IgG, IgM (PERFIL)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,170.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "INMUNOGLOBULINA IgA, IgG, IgM (PERFIL)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$870.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "INMUNOGLOBULINA M IgM", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$240.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "INSULINA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$360.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "LIPASA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$500.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "LIPOPROTEÍNA A", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,430.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Uroanálisis", nombre: "MAGNESIO EN ORINA DE 24 HRS.", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$140.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "MAGNESIO (Mg)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$265.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Radiología", nombre: "MANDIBULA (MAXILAR)", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "MANO AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "MANO BILATERAL 2 PROYECCIONES", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Marcadores Tumorales", nombre: "MARCADOR TUMORAL I", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,280.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "MARCADOR TUMORAL II", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,310.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "MARCADOR TUMORAL IV", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$890.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "MARCADOR TUMORAL V", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$940.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "MARCADOR TUMORAL VI", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$810.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "MARCADOR TUMORAL VII", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,785.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "MARCADOR TUMORAL VIII", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,840.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Mastografía", nombre: "MASTOGRAFIA", tipo: "Mastografía", indicacion: "ESPECIALES", precio: "$1,050.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Uroanálisis", nombre: "MICROALBUMINURIA", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$520.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Uroanálisis", nombre: "MICROALBUMINURIA EN ORINA OCASIONAL", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$440.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Radiología", nombre: "MUÑECA AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "MUÑECA BILATERAL AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "OMÓPLATO AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "OMÓPLATO BILATERAL AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Toxicología", nombre: "OPIACEOS", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$140.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Uroanálisis", nombre: "OXALATOS EN ORINA DE 24 HRS", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$1,540.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Perfiles y Paquetes", nombre: "PAQUETE COVID", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$1,940.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Perfiles y Paquetes", nombre: "PAQUETE (COVID E INFLUENZA)", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$1,155.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Radiología", nombre: "PAQUETE MUJER (MASTO Y USG MAMARIO)", tipo: "Radiología", indicacion: "ESPECIALES", precio: "$1,430.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Hormonas", nombre: "PARATHORMONA (PTH RP)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$6,190.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "PARATOHORMONA (PTH, MOLECULA INTACTA)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$950.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "PCR DETECCIÓN CROMOSOMA FILADELFIA BCR/ABL", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$4,620.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "PCR DETECCIÓN MYCOBACTERIUM TUBERCULOSIS", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$3,300.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Inmunología", nombre: "PCR VIRUS DEL PAPILOMA HUMANO 28 GENOTIPOS*", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$6,200.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Inmunología", nombre: "PCR VIRUS DE PAPILOMA HUMANO ALTO RIESGO-RT", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$2,555.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Radiología", nombre: "PÉLVIS AP", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "PÉLVIS AP – LAT (2 PROYECCIONES)", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "PÉLVIS AP Y OBLICUAS", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,270.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "PÉLVIS EN ABDUCCIÓN Y ROTACIÓN", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Química Sanguínea", nombre: "PEPTIDO C", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$720.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "PÉPTIDO NATRIURÉTICO CEREBRAL (BNP)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,325.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL ALERGIA ALIMENTICIO (40 ELEMENTOS)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$6,190.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL ALERGIA ALIMENTICIO E INHALATORIO (90 E)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$13,600.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL ALERGIA INHALATORIO (40 ELEMENTOS)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$6,035.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL CARDÍACO I", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$715.00", desc: "No requiere preparación previa." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL CARDÍACO II", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$990.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL CARDÍACO III", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,755.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL DE ANDROGENOS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,470.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL DE ANEMIA I", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,490.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL DE ANEMIA II", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,630.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL DE HIERRRO I", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$530.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL DE HIERRRO II", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$655.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL DE HIERRRO III", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$975.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL DE LIPÍDOS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$970.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL GINECOLÓGICO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$970.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL HEPÁTICO I", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$690.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL HEPÁTICO II", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$880.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL HEPÁTICO III", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,080.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL HEPÁTICO NIÑOS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$760.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL HORMONAL COMPLETO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$2,820.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL HORMONAL COMPLETO II", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,630.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL HORMONAL FEMENINO (GINECO Y TIROIDEO)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$2,200.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL HORMONAL MASCULINO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,200.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Radiología", nombre: "PERFILOGRAFÍA LAT Y WATTERS", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL PRECLAMPTICO", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$1,540.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL PRENATAL", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$770.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL PREOPERATORIO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$935.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "PERFIL PROSTÁTICO II", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,050.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL REUMATOLÓGICO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$750.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL TIROIDEO II", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,030.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL TORCH IgG", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$2,600.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL TORCH IgG, IgM", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$3,610.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL TORCH IgM", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$2,150.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "PERFIL TOXEMICO", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$2,850.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Radiología", nombre: "PIE AP Y OBLICUA", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "PIE BILATERAL AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "PIE BILATERAL AP – LAT, CON APOYO", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "PLACA OBSTÉTRICA", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Hematología", nombre: "PLAQUETAS", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$155.00", desc: "No requiere preparación previa." },
  { cat: "Química Sanguínea", nombre: "POTASIO EN SUERO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$400.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "PREALBUMINA (PAB)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,170.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "PRO-CALCITONINA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,640.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "PROGESTERONA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$270.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "PROLACTINA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$320.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "PROTEINA A PLACENTARIA (PAPP)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,030.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "PROTEÍNA C REACTIVA (PCR)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$385.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "PROTEÍNA C REACTIVA ULTRASENSIBLE", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$660.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hematología", nombre: "PROTEÍNA S DE LA COAGULACIÓN", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$2,290.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Uroanálisis", nombre: "PROTEÍNAS TOTALES EN ORINA DE 24 h.", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$550.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "PROTEÍNAS TOTALES EN SUERO Y REL A/G", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$440.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "PRUEBA COVID (ANTIGENO)", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$800.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "PRUEBA COVID (SANGUINEA)", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$770.00", desc: "No requiere preparación previa." },
  { cat: "Hematología", nombre: "PRUEBAS CRUZADAS (POR DONADOR)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$570.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "QUÍMICA SANGUÍNEA 12 ELEMENTOS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,375.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "QUÍMICA SANGUÍNEA 29 ELEMENTOS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,550.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "QUÍMICA SANGUÍNEA 32 ELEMENTOS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,970.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "QUÍMICA SANGUÍNEA 35 ELEMENTOS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$2,540.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "QUÍMICA SANGUÍNEA 3 ELEMENTOS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$400.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "QUÍMICA SANGUÍNEA 40 ELEMENTOS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$3,050.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "QUÍMICA SANGUÍNEA 45 ELEMENTOS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$3,290.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "QUÍMICA SANGUÍNEA 4 ELEMENTOS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$550.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "QUÍMICA SANGUÍNEA 5 ELEMENTOS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$715.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "QUÍMICA SANGUÍNEA 6 ELEMENTOS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$860.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "QUÍMICA SANGUÍNEA 8 ELEMENTOS", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,160.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "QUÍNTUPLE MARCADOR", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$9,550.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Inmunología", nombre: "REACCIONES FEBRILES", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$320.00", desc: "No requiere preparación previa." },
  { cat: "Hormonas", nombre: "RESISTENCIA A LA INSULINA (HOMA)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$460.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hematología", nombre: "RETICULOCITOS", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$170.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "RODILLA AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "RODILLA BILATERAL 1 PROYECCIÓN", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "RODILLA BILATERAL 2 PROYECCIONES", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "RODILLA BILATERAL – TANGENCIAL 30°, 60° Y 90°", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,270.00", desc: "No requiere preparación previa." },
  { cat: "Química Sanguínea", nombre: "ROSA DE BENGALA", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$220.00", desc: "No requiere preparación previa." },
  { cat: "Microbiología", nombre: "ROTAVIRUS EN HECES", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$560.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Microbiología", nombre: "SANGRE OCULTA EN HECES Ó PRUEBA DE GUAYACO", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$170.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Radiología", nombre: "SENOS PARANASALES 1 PROYECCIÓN", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "SENOS PARANASALES 2 PROYECCIONES", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "SENOS PARANASALES 3 PROYECCIONES", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,270.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "SERIE CARDÍACA", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,860.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "SERIE ESOFAGOGASTRODUODENAL", tipo: "Radiología", indicacion: "ESPECIALES", precio: "$2,780.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Radiología", nombre: "SIALOGRAFIA POR RX", tipo: "Radiología", indicacion: "ESPECIALES", precio: "$3,390.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Hormonas", nombre: "SOMATOMEDINA C (IGF-1)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$825.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "SOMATOMEDINA IGF BP-3", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,890.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Tomografía", nombre: "TAC DE ABDOMEN TOTAL SIMPLE", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$4,150.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE ABDOMEN TOTAL SIMPLE Y CONTRASTADA", tipo: "Tomografía", indicacion: "AYUNO", precio: "$5,150.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Tomografía", nombre: "TAC DE ANGIOGRAFÍA DE TÓRAX, CRÁNEO, ETC", tipo: "Tomografía", indicacion: "AYUNO", precio: "$6,090.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Tomografía", nombre: "TAC DE CEFALOPELVIMETRÍA", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$1,850.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE COLUMNA CERVICAL", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$6,750.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE COLUMNA COMPLETA", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$10,100.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE COLUMNA DORSAL", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$6,750.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE COLUMNA LUMBAR", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$6,750.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE CRÁNEO SIMPLE", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$2,900.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE CRÁNEO SIMPLE CON VENTANA ÓSEA", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$2,900.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE CRÁNEO SIMPLE EN 3 “D”", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$4,160.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE CRÁNEO SIMPLE Y CONTRASTADO", tipo: "Tomografía", indicacion: "AYUNO", precio: "$3,700.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Tomografía", nombre: "TAC DE CUELLO SIMPLE", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$3,670.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE CUELLO SIMPLE Y CONTRASTADA", tipo: "Tomografía", indicacion: "AYUNO", precio: "$4,560.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Tomografía", nombre: "TAC DE DINÁMICA DE PÁNCREAS", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$6,580.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE ESCÁPULA", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$4,820.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE MACIZO FACIAL, OÍDOS", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$6,090.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE ÓRBITAS COMPARATIVAS, CORTES FINOS", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$6,090.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE ORTOPANTOMOGRAFÍA", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$1,850.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE PÉLVIS, RODILLA, FÉMUR, TOBILLO, ETC", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$5,150.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE SENOS PARANASALES", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$3,600.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE SILLA TURCA", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$5,150.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE TÓRAX SIMPLE", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$4,180.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC DE TÓRAX SIMPLE Y CONTRASTADA", tipo: "Tomografía", indicacion: "AYUNO", precio: "$5,150.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Tomografía", nombre: "TAC TORACO-ABDOMINAL SIMPLE", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$6,090.00", desc: "No requiere preparación previa." },
  { cat: "Tomografía", nombre: "TAC TORACO-ABDOMINAL SIMPLE Y CONTRASTADA", tipo: "Tomografía", indicacion: "AYUNO", precio: "$6,250.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Perfiles y Paquetes", nombre: "TAMIZ BÁSICO", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$870.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Perfiles y Paquetes", nombre: "TAMIZ DE GLUCOSA", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$415.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Perfiles y Paquetes", nombre: "TAMIZ METABÓLICO NEONATAL AMPLIADO", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$2,020.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Perfiles y Paquetes", nombre: "TAMIZ METABÓLICO NEONATAL AMPLIADO COMPLETO", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$2,860.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Radiología", nombre: "TELE DE TÓRAX AP (RESPIRATORIO)", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Hormonas", nombre: "TESTOSTERONA LIBRE", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$565.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "TESTOSTERONA TOTAL", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$330.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Radiología", nombre: "TIBIA Y PERONÉ AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "TIBIA Y PERONÉ BILATERAL", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,150.00", desc: "No requiere preparación previa." },
  { cat: "Hematología", nombre: "TIEMPO DE PROTROMBINA (TP)", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$240.00", desc: "No requiere preparación previa." },
  { cat: "Hematología", nombre: "TIEMPO DE SANGRADO Y COAGULACIÓN", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$85.00", desc: "No requiere preparación previa." },
  { cat: "Hematología", nombre: "TIEMPO DE TROMBOPLASTINA PARCIAL (TPT)", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$240.00", desc: "No requiere preparación previa." },
  { cat: "Hematología", nombre: "TIEMPOS DE COAGULACIÒN", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$420.00", desc: "No requiere preparación previa." },
  { cat: "Hormonas", nombre: "TIROGLOBULINA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$520.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "TIROXINA LIBRE (T4 LIBRE)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$330.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "TIROXINA TOTAL (T4 TOTAL)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$270.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Radiología", nombre: "TOBILLO AP – LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "TOBILLO AP – LAT Y OBLICUA", tipo: "Radiología", indicacion: "NINGUNA", precio: "$790.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "TOBILLO BILATERAL AP Y LAT", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "TORAX OSEO AP", tipo: "Radiología", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Radiología", nombre: "TÓRAX ÓSEO AP Y OBLICUA", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Química Sanguínea", nombre: "TRANSAMINASA GLUTÁMICO PIRÚVICA (TGP) (ALT)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$220.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "TRANSAMINAS GLUTÁMICO OXALACETICO (TGO) (AST)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$220.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "TRANSFERRINA", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$340.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Radiología", nombre: "TRÁNSITO INTESTINAL", tipo: "Radiología", indicacion: "ESPECIALES", precio: "$2,530.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "TRIGLICÉRIDOS EN SUERO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$400.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Marcadores Tumorales", nombre: "TRIPLE MARCADOR", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$3,130.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Hormonas", nombre: "TRIYODOTIRONINA LIBRE T3 (T3 LIBRE)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$225.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Hormonas", nombre: "TRIYODOTIRONINA TOTAL T3 (T3 TOTAL)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$310.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "TROPONINA", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$800.00", desc: "No requiere preparación previa." },
  { cat: "Hormonas", nombre: "T-UPTAKE (TU)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$190.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO ABDOMINAL", tipo: "Ultrasonido", indicacion: "AYUNO", precio: "$1,320.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO APENDICULAR", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$750.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO CADERA", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$2,420.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO CAROTIDEO DOPPLER", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$2,990.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO CROMOSOMICO/GENETICO", tipo: "Ultrasonido", indicacion: "ESPECIALES", precio: "$1,815.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO CUELLO", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,210.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO DE PENE CON FLUJOMETRÍA", tipo: "Ultrasonido", indicacion: "ESPECIALES", precio: "$1,650.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO DE PULMON", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,980.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO DOPPLER ACRESENTISMO PLACENTA", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,150.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO DOPPLER ARTERIAL Y VENOSO", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$3,600.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO DOPPLER MP ARTERIAL", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$2,800.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO DOPPLER MP VENOSO", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$2,800.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO ESTRUCTURAL", tipo: "Ultrasonido", indicacion: "ESPECIALES", precio: "$2,420.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO FAST", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,150.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO GENÉTICO OBSTÉTRICO", tipo: "Ultrasonido", indicacion: "ESPECIALES", precio: "$2,420.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO GINECOLÓGICO/PELVICO", tipo: "Ultrasonido", indicacion: "VEJIGA LLENA", precio: "$660.00", desc: "Preséntate con la vejiga llena, sin orinar antes del estudio." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO HEPÁTICO DOPPLER/HEPATOPORTAL", tipo: "Ultrasonido", indicacion: "AYUNO", precio: "$1,815.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO HEPATOBILIAR (ABD. SUP.)", tipo: "Ultrasonido", indicacion: "AYUNO", precio: "$935.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO HEPATOBILIAR DOPPLER", tipo: "Ultrasonido", indicacion: "AYUNO", precio: "$1,815.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO HEPATOBILIAR (PRUEBA DE BOYDEN)", tipo: "Ultrasonido", indicacion: "AYUNO", precio: "$1,150.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO HEPATOESPLENICO", tipo: "Ultrasonido", indicacion: "AYUNO", precio: "$950.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO HEPATO - RENAL", tipo: "Ultrasonido", indicacion: "AYUNO", precio: "$950.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO INGUINAL", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,150.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO INGUINOESCROTAL", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,815.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO MAMARIO", tipo: "Ultrasonido", indicacion: "ESPECIALES", precio: "$870.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO MANGUITO ROTADOR", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$2,420.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO MIEMBRO SUP. DOPPLER (Fistula)", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$2,990.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO MÚSCULO ESQUELÉTICO", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$2,420.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO OBSTÉTRICO", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$660.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO OBSTETRICO CON PERFIL BIOFISICO", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$915.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO OBSTÉTRICO DE 4 “D”", tipo: "Ultrasonido", indicacion: "ESPECIALES", precio: "$970.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO OBSTÉTRICO DOPPLER", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,375.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO OBSTÉTRICO DOPPLER/PERFIL BIO.", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,490.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO OBSTETRICO TRANSVAGINAL", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO PARED ABDOMINAL", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,150.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO PARTES BLANDAS", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,150.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO PENE", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,210.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO PILORO", tipo: "Ultrasonido", indicacion: "AYUNO", precio: "$2,180.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO PROSTÁTICO SUPRAPÚVICO", tipo: "Ultrasonido", indicacion: "VEJIGA LLENA", precio: "$880.00", desc: "Preséntate con la vejiga llena, sin orinar antes del estudio." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO PROSTÁTICO TRANSRECTAL", tipo: "Ultrasonido", indicacion: "ESPECIALES", precio: "$1,150.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO RENAL", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$730.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO RENAL DOPPLER", tipo: "Ultrasonido", indicacion: "ESPECIALES", precio: "$1,815.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO SUPRARRENAL", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,150.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO TENDON DE AQUILES", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,815.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO TESTICULAR (TESTICULAR DOPPLER)", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$915.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO TIROIDEO (TIROIDEO DOPPLER)", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,150.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO TRANSFONTANELAR", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,150.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO TRANSVAGINAL", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,100.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO TRANSVAGINAL FOLICULAR", tipo: "Ultrasonido", indicacion: "ESPECIALES", precio: "$1,815.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Ultrasonido", nombre: "ULTRASONIDO YUGULAR DOPPEL", tipo: "Ultrasonido", indicacion: "NINGUNA", precio: "$1,815.00", desc: "No requiere preparación previa." },
  { cat: "Uroanálisis", nombre: "UREA EN ORINA DE 24 HRS.", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$100.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Química Sanguínea", nombre: "UREA EN SUERO", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$165.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Radiología", nombre: "URETROCISTOGRAMA", tipo: "Radiología", indicacion: "ESPECIALES", precio: "$2,660.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Radiología", nombre: "URETROCISTOGRAMA (URETROGRAFÍA)", tipo: "Radiología", indicacion: "ESPECIALES", precio: "$2,900.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Radiología", nombre: "URETROGRAFIA DINAMICA", tipo: "Radiología", indicacion: "ESPECIALES", precio: "$3,025.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Microbiología", nombre: "UROCULTIVO", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$640.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Radiología", nombre: "UROGRAFÍA EXCRETORA", tipo: "Radiología", indicacion: "ESPECIALES", precio: "$2,780.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Tomografía", nombre: "UROTAC CONTRASTADA (CORTES FINOS)", tipo: "Tomografía", indicacion: "AYUNO", precio: "$6,090.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Tomografía", nombre: "UROTAC SIMPLE", tipo: "Tomografía", indicacion: "NINGUNA", precio: "$5,150.00", desc: "No requiere preparación previa." },
  { cat: "Ultrasonido", nombre: "USG HEPATICO C/ELASTOGRAFIA", tipo: "Ultrasonido", indicacion: "AYUNO", precio: "$1,155.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "V.D.R.L. (ANTICUERPOS ANTI REAGINAS)", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$155.00", desc: "No requiere preparación previa." },
  { cat: "Hematología", nombre: "VELOCIDAD DE SEDIMENTACIÓN GLOBULAR (V.S.G.)", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$165.00", desc: "No requiere preparación previa." },
  { cat: "Inmunología", nombre: "VIH", tipo: "Laboratorio", indicacion: "NINGUNA", precio: "$580.00", desc: "No requiere preparación previa." },
  { cat: "Química Sanguínea", nombre: "VITAMINA D 1, 25 OH (CALCITRIOL)", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$5,320.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "VITAMINA D 25 HIDROXI", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$1,000.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Inmunología", nombre: "VPH POR PCR (HOMBRE Y MUJER) 14 GENOTIPOS", tipo: "Laboratorio", indicacion: "ESPECIALES", precio: "$4,260.00", desc: "Requiere indicaciones especiales; consulta con el laboratorio antes de tu cita." },
  { cat: "Radiología", nombre: "WATTERS", tipo: "Radiología", indicacion: "NINGUNA", precio: "$550.00", desc: "No requiere preparación previa." },
  { cat: "Inmunología", nombre: "WESTERN BLOT HIV 1", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$4,825.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
  { cat: "Química Sanguínea", nombre: "ZINC", tipo: "Laboratorio", indicacion: "AYUNO", precio: "$970.00", desc: "Requiere ayuno de 8 a 12 horas previo a la toma de muestra." },
];

export const categoriasOrden = [
  "Perfiles y Paquetes",
  "Química Sanguínea",
  "Hematología",
  "Inmunología",
  "Hormonas",
  "Marcadores Tumorales",
  "Microbiología",
  "Uroanálisis",
  "Toxicología",
  "Anatomía Patológica",
  "Radiología",
  "Tomografía",
  "Ultrasonido",
  "Mastografía",
];
